DROP TABLE IF EXISTS employee;

CREATE TABLE employee (
    EID INT AUTO_INCREMENT PRIMARY KEY,
    DID INT NOT NULL,
    PID INT NOT NULL,
    EName CHAR(20) NOT NULL,
    Sex CHAR(2) CHECK (Sex IN ('男', '女')),
    Phone CHAR(11) UNIQUE,
    Password CHAR(20) NOT NULL
);